/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpendTrackersImport } from './routes/spend-trackers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SpendTrackersRoute = SpendTrackersImport.update({
  id: '/spend-trackers',
  path: '/spend-trackers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/spend-trackers': {
      id: '/spend-trackers'
      path: '/spend-trackers'
      fullPath: '/spend-trackers'
      preLoaderRoute: typeof SpendTrackersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spend-trackers': typeof SpendTrackersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spend-trackers': typeof SpendTrackersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/spend-trackers': typeof SpendTrackersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spend-trackers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spend-trackers'
  id: '__root__' | '/' | '/spend-trackers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpendTrackersRoute: typeof SpendTrackersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpendTrackersRoute: SpendTrackersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/spend-trackers"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/spend-trackers": {
      "filePath": "spend-trackers.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
