import { format, subDays } from "date-fns";
import { Account, Category, Transaction } from "./types";

const today = new Date(Date.now());
const dateFormatted = (sub: number) =>
  format(subDays(today, sub), "yyyy-MM-dd");

export const accounts: Account[] = [
  {
    account_id: "1",
    balances: {
      available: 110.94,
      current: 110.94,
      iso_currency_code: "USD",
    },
    name: "Plaid Checking",
    official_name: "Plaid Gold Standard 0% Interest Checking",
    subtype: "checking",
    type: "depository",
  },
  {
    account_id: "2",
    balances: {
      available: 2000.34,
      current: 2028.34,
      iso_currency_code: "USD",
    },
    name: "Demo Bank",
    official_name: "Demo Bank Financial Inc. Spending Account",
    subtype: "checking",
    type: "depository",
  },
];

export const transactions: Transaction[] = [
  {
    account_id: "1",
    amount: 28.34,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(1),
    authorized_date: dateFormatted(0),
    name: "Dd Doordash Burgerking",
    merchant_name: "Burger King",
    merchant_entity_id: "mVrw538wamwdm22mK8jqpp7qd5br0eeV9o4a1",
    logo_url: "https://plaid-merchant-logos.plaid.com/burger_king_155.png",
    website: "burgerking.com",
    payment_channel: "online",
    pending: true,
    pending_transaction_id: null,
  },
  {
    account_id: "2",
    amount: 72.1,
    iso_currency_code: "USD",
    category_id: "2",
    date: dateFormatted(2),
    authorized_date: dateFormatted(1),
    name: "PURCHASE WM SUPERCENTER #1700",
    merchant_name: "Walmart",
    merchant_entity_id: "O5W5j4dN9OR3E6ypQmjdkWZZRoXEzVMz2ByWM",
    logo_url: "https://plaid-merchant-logos.plaid.com/walmart_1100.png",
    website: "walmart.com",
    payment_channel: "in store",
    pending: false,
    pending_transaction_id: "no86Eox18VHMvaOVL7gPUM9ap3aR1LsAVZ5nc",
  },
  {
    account_id: "2",
    amount: 30,
    iso_currency_code: "USD",
    category_id: "1",
    date: dateFormatted(3),
    authorized_date: dateFormatted(2),
    name: "Shake Shack",
    merchant_name: "Shake Shack",
    merchant_entity_id: "NXAJN1bDAZYjpDKY7Wr5JjzVmV7nnVY171jze",
    logo_url: "https://plaid-merchant-logos.plaid.com/shake_shack_887.png",
    website: "shakeshack.com",
    payment_channel: "in store",
    pending: false,
    pending_transaction_id: "jdkWZZRoXEzVVHMvaOVL7gPUM9ap3aR1LsAVZ5nc",
  },
  {
    account_id: "1",
    amount: 150,
    iso_currency_code: "USD",
    category_id: "5",
    date: dateFormatted(4),
    authorized_date: dateFormatted(3),
    name: "Instacart",
    merchant_name: "Instacart",
    merchant_entity_id: "5JjzVmV7nnVY171jzeNXAJN1bDAZYjpDKY7Wr",
    logo_url: "",
    website: "instacart.com",
    payment_channel: "online",
    pending: false,
    pending_transaction_id: "ap3aR1LsAVZ5ncjdkWZZRoXEzVVHMvaOVL7gPUM9",
  },
  {
    account_id: "1",
    amount: 13.99,
    iso_currency_code: "USD",
    category_id: "3",
    date: dateFormatted(5),
    authorized_date: dateFormatted(4),
    name: "Udemy",
    merchant_name: "Udemy",
    merchant_entity_id: "nnVY171jzeNXAJN5JjzVmV71bDAZYjpDKY7Wr",
    logo_url: "",
    website: "udemy.com",
    payment_channel: "online",
    pending: false,
    pending_transaction_id: "ap3aR1LsAVRoXEzVVHMvZ5ncjdkWZZaOVL7gPUM9",
  },
  {
    account_id: "1",
    amount: 15,
    iso_currency_code: "USD",
    category_id: "4",
    date: dateFormatted(6),
    authorized_date: dateFormatted(5),
    name: "Lyft",
    merchant_name: "Lyft",
    merchant_entity_id: "JN5nnVY171jzeNXA7WrJjzVmV71bDAZYjpDKY",
    logo_url: "",
    website: "lyft.com",
    payment_channel: "online",
    pending: false,
    pending_transaction_id: "cjdkWZap3aR1RoXEzVVHMvZ5nZaOVL7gPLsAVUM9",
  },
];

export const categories: Category[] = [
  {
    id: "1",
    name: "Food",
  },
  {
    id: "2",
    name: "Shopping",
  },
  {
    id: "3",
    name: "Education",
  },
  {
    id: "4",
    name: "Transportation",
  },
  {
    id: "5",
    name: "Groceries",
  },
];
